# HTTP proxy端口
port: 7890 

# SOCKS5 proxy端口, 0代表关闭
socks-port: 0

# Linux 和 macOS 的 redir proxy端口, 0代表关闭
redir-port: 0

# 允许局域网的连接
allow-lan: true

# 规则模式：rule（规则） / global（全局proxy）/ direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info


# 您可以将静态网页资源放置在一个目录中，bin/amd64将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
external-ui: /root/src/dashboard

# RESTful API 位置
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: 123456789

proxies:
  -

proxy-groups:
  -

rules:
 - 